apiVersion: v1
kind: Namespace
metadata:
  name: hk-tourism-ai
  labels:
    name: hk-tourism-ai
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    environment: production